backend:
  name: github
  repo: suhcodes/qdmblog
  branch: master
media_folder: ".vuepress/public/assets/img"
public_folder: "../../"
display_url: https://qdmblog.netlify.app
collections:
  - name: "post"
    label: "Post"
    folder: "docs/_posts"
    create: true
    slug: "{{slug}}"
    show_preview_links: true
    preview_path: "blog/preview/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured Image", name: "featuredimg", widget: "image"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Lang", name: "lang", widget: "string"}
      - {label: "Sidebar", name: "sidebar", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}